name: DotNet
on:

  push:
    branches: [test-562]
  # workflow_dispatch:
  #   inputs:
  #     buildArgs:
  #       description: 'Arguments for the build'
  #       required: false
  #       default: ''

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      # - name: Run Uno Check
      #   shell: pwsh
      #   run: |
      #     dotnet tool install --global Uno.Check --version 1.25.1
      #     uno-check -v --ci --non-interactive --fix --verbose --skip xcode --skip gtk3 --skip vswin --skip androidemulator --skip androidsdk --skip vsmac --skip dotnetnewunotemplates

      - name: Verify .NET SDK Version
        run: dotnet --version
      - name: List Installed .NET SDK Versions
        run: dotnet --list-sdks
      # - name: Setup MSBuild
      #   uses: microsoft/setup-msbuild@v2

      # - name: Build Packages
      #   shell: pwsh
      #   run: |
      #     msbuild ./dotnet-hello-world.sln /r /p:Configuration=Release 
      # - name: Run Tests
      #   shell: pwsh
      #   run: |
      #     dotnet test ./dotnet-hello-world.sln
      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
